### ISSUE TITLE
Composer errors on install

### ISSUE THREAD

**Issue by robwent** [Vardot/vardoc#10]
Just trying to test this out, but composer reports errors when trying to install the package:

    [Exception]
    Cannot apply patch Issue #1356276: Allow profiles to provide a base_parent profile and load them
     in the correct order (https://www.drupal.org/files/issues/1356276-408--8.4.3.patch)!

I don't really know Drupal but it seems related to this: https://www.drupal.org/project/drupal/issues/1356276

**Comment by robwent** [comment]
I changed the composer file to:

    "composer-exit-on-patch-failure": false

and it seemed to install ok, the autoload files are generated, but then it fails on:

    'xargs' is not recognized as an internal or external command, operable program or batch file.

Am I right in saying that this isn't installable on a Windows machine?

**Comment by Natshah** [comment]
Having "composer-exit-on-patch-failure": false is not good for the project
As you may have some patches which did not patch and no Error will show up
This why we do have it.

Please check your php, composer and git versions

## php --version

```
rajab@vardot-dev:~$ php --version
PHP 7.1.11-0ubuntu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.11-0ubuntu0.17.10.1, Copyright (c) 1999-2017, by Zend Technologies
```

## composer --version
```
rajab@vardot-dev:~$ composer --version
Composer version 1.6.2 2018-01-05 15:28:41
```
## to update composer

`$ composer self-update`

Please make sure that your do have the right file permissions in your global composer, and the composer cache

## git --version
```
rajab@vardot-dev:~$ git --version
git version 2.15.1
```

**Comment by robwent** [comment]
The versions aren't going to make any difference if Windows doesn't understand the xargs command.

Should this install on a Windows machine?

**Comment by Natshah** [comment]
Aha It's Windows
Try to Enable Bash and Linux commands for Developers in Windows

[How to Install and Use the Linux Bash Shell on Windows 10](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)

and search for xargs' is not recognized on windows.

**Comment by robwent** [comment]
To be honest, I just wanted to install quickly to compare it to other systems out there, but it looks like I might not need anything now anyway.

Thanks for the bash link, I'll check that out.

**Comment by Natshah** [comment]
Welcome
